=== SpaceTeam/fms-gui-web/fms-gui-web/src/assets/xml/FMS.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FMS" type="FMSType"/>
  <xs:complexType name="PowerType">
    <xs:sequence>
      <xs:element type="xs:double" name="Voltage"/>
      <xs:element type="xs:double" name="VoltageCell"/>
      <xs:element type="xs:double" name="Current"/>
    </xs:sequence>
    <xs:attribute type="xs:time" name="LocalTimestamp"/>
  </xs:complexType>
  <xs:complexType name="ConnectionQualitySensType">
    <xs:sequence>
      <xs:element type="xs:double" name="Quality"/>
    </xs:sequence>
    <xs:attribute type="xs:time" name="LocalTimestamp"/>
  </xs:complexType>
  <xs:complexType name="FlagsType">
    <xs:sequence>
      <xs:element type="xs:boolean" name="adc_initialized"/>
      <xs:element type="xs:boolean" name="dac_initialized"/>
      <xs:element type="xs:boolean" name="dma_initialized"/>
      <xs:element type="xs:boolean" name="flash_ssp_initialized"/>
      <xs:element type="xs:boolean" name="i2c0_initialized"/>
      <xs:element type="xs:boolean" name="i2c1_initialized"/>
      <xs:element type="xs:boolean" name="i2c2_initialized"/>
      <xs:element type="xs:boolean" name="uart0_initialized"/>
      <xs:element type="xs:boolean" name="uart1_initialized"/>
      <xs:element type="xs:boolean" name="uart2_initialized"/>
      <xs:element type="xs:boolean" name="uart3_initialized"/>
      <xs:element type="xs:boolean" name="rtc_initialized"/>
      <xs:element type="xs:boolean" name="ssp1_initialized"/>
      <xs:element type="xs:boolean" name="structs_initialized"/>
      <xs:element type="xs:boolean" name="systick_initialized"/>
      <xs:element type="xs:boolean" name="timer1_initialized"/>
      <xs:element type="xs:boolean" name="watchdog_initialized"/>
      <xs:element type="xs:boolean" name="eeprom_initialized"/>
      <xs:element type="xs:boolean" name="ars_initialized"/>
      <xs:element type="xs:boolean" name="power_management_initialized"/>
      <xs:element type="xs:boolean" name="flash_initialized"/>
      <xs:element type="xs:boolean" name="seven_segment_intern_initialized"/>
      <xs:element type="xs:boolean" name="seven_segment_extern_initialized"/>
      <xs:element type="xs:boolean" name="startup_success"/>
      <xs:element type="xs:boolean" name="sensor_pressure_initialized"/>
      <xs:element type="xs:boolean" name="startup_checked"/>
      <xs:element type="xs:boolean" name="sensor_imu_initialized"/>
      <xs:element type="xs:boolean" name="sensor_tmp100_initialized"/>
      <xs:element type="xs:boolean" name="sensor_hig_initialized"/>
      <xs:element type="xs:boolean" name="sensor_gyro_initialized"/>
      <xs:element type="xs:boolean" name="gnss_initialized"/>
      <xs:element type="xs:boolean" name="servo_initialized_all"/>
      <xs:element type="xs:boolean" name="pwm_initialized"/>
      <xs:element type="xs:boolean" name="afs_initialized"/>
      <xs:element type="xs:boolean" name="camera_initialized"/>
      <xs:element type="xs:boolean" name="sensor_current_initialized"/>
      <xs:element type="xs:boolean" name="igniter_initialized"/>
      <xs:element type="xs:boolean" name="separation_detection_initialized"/>
      <xs:element type="xs:boolean" name="servo_configured"/>
      <xs:element type="xs:boolean" name="igniter_configured"/>
      <xs:element type="xs:boolean" name="igniter_1_fired"/>
      <xs:element type="xs:boolean" name="igniter_2_fired"/>
      <xs:element type="xs:boolean" name="igniter_3_fired"/>
      <xs:element type="xs:boolean" name="igniter_4_fired"/>
      <xs:element type="xs:boolean" name="igniter_1_firing"/>
      <xs:element type="xs:boolean" name="igniter_2_firing"/>
      <xs:element type="xs:boolean" name="igniter_3_firing"/>
      <xs:element type="xs:boolean" name="igniter_4_firing"/>
      <xs:element type="xs:boolean" name="igniter_armed"/>
      <xs:element type="xs:boolean" name="igniter_1_connected"/>
      <xs:element type="xs:boolean" name="igniter_2_connected"/>
      <xs:element type="xs:boolean" name="igniter_3_connected"/>
      <xs:element type="xs:boolean" name="igniter_4_connected"/>
      <xs:element type="xs:boolean" name="ars_enabled"/>
      <xs:element type="xs:boolean" name="camera_on"/>
      <xs:element type="xs:boolean" name="gnss_powersave"/>
      <xs:element type="xs:boolean" name="flash_erased"/>
      <xs:element type="xs:boolean" name="flash_store_data"/>
      <xs:element type="xs:boolean" name="radio_on"/>
      <xs:element type="xs:boolean" name="radio_tx_active"/>
      <xs:element type="xs:boolean" name="flash_flight_header_written"/>
      <xs:element type="xs:boolean" name="timer1_running"/>
      <xs:element type="xs:boolean" name="rtc_synchronized"/>
      <xs:element type="xs:boolean" name="usb_connection_detected"/>
      <xs:element type="xs:boolean" name="watchdog_timeout_occured"/>
      <xs:element type="xs:boolean" name="flash_full"/>
      <xs:element type="xs:boolean" name="crystal_oszillator_used"/>
      <xs:element type="xs:boolean" name="liftoff_detected"/>
      <xs:element type="xs:boolean" name="gnss_fix"/>
      <xs:element type="xs:boolean" name="rocket_panic"/>
      <xs:element type="xs:boolean" name="mainchute_altitude_detected"/>
      <xs:element type="xs:boolean" name="eagle_landed"/>
      <xs:element type="xs:boolean" name="rocket_is_stable"/>
      <xs:element type="xs:boolean" name="apogee_detected_by_kalman"/>
      <xs:element type="xs:boolean" name="recovery_mode"/>
      <xs:element type="xs:boolean" name="check_stability_executed"/>
      <xs:element type="xs:boolean" name="config_intialized"/>
      <xs:element type="xs:boolean" name="stages_separated"/>
      <xs:element type="xs:boolean" name="igniter_hpower_fired"/>
      <xs:element type="xs:boolean" name="igniter_hpower_firing"/>
      <xs:element type="xs:boolean" name="igniter_hpower_connected"/>
      <xs:element type="xs:boolean" name="reset_during_flight"/>
      <xs:element type="xs:boolean" name="housekeeping_data_read"/>
      <xs:element type="xs:boolean" name="mbb_satcom_configured"/>
      <xs:element type="xs:boolean" name="mbb_satcom_initialized"/>
      <xs:element type="xs:boolean" name="mbb_cameras_configured"/>
      <xs:element type="xs:boolean" name="mbb_cameras_initialized"/>
      <xs:element type="xs:boolean" name="power_management_operational"/>
      <xs:element type="xs:boolean" name="rail_5v_enabled"/>
      <xs:element type="xs:boolean" name="padding1"/>
      <xs:element type="xs:boolean" name="padding2"/>
      <xs:element type="xs:boolean" name="battery_overvoltage"/>
      <xs:element type="xs:boolean" name="battery_only_attached"/>
      <xs:element type="xs:boolean" name="rail_3v3_sensor_enabled"/>
      <xs:element type="xs:boolean" name="rail_3v3_gnss_enabled"/>
      <xs:element type="xs:boolean" name="rail_3v3_external_enabled"/>
      <xs:element type="xs:boolean" name="cmd_buffer_overrun"/>
      <xs:element type="xs:boolean" name="eeprom_page_cycle_overflow"/>
      <xs:element type="xs:boolean" name="flash_dma_buffer_overrun"/>
      <xs:element type="xs:boolean" name="flash_write_error"/>
      <xs:element type="xs:boolean" name="i2c_job_buffer_overflow"/>
      <xs:element type="xs:boolean" name="i2c_interrupt_handler_error"/>
      <xs:element type="xs:boolean" name="interrupt_interference"/>
      <xs:element type="xs:boolean" name="uart0_tx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart0_rx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart1_tx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart1_rx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart2_tx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart2_rx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart3_tx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="uart3_rx_buffer_overflow"/>
      <xs:element type="xs:boolean" name="ssp1_interrupt_ror"/>
      <xs:element type="xs:boolean" name="ssp1_interrupt_unknown_device"/>
      <xs:element type="xs:boolean" name="ssp1_buffer_overflow"/>
      <xs:element type="xs:boolean" name="watchdog_interrupt_handler_hit"/>
      <xs:element type="xs:boolean" name="flight_substate_default_handler_hit"/>
      <xs:element type="xs:boolean" name="rocket_state_default_handler_hit"/>
      <xs:element type="xs:boolean" name="struct_size_overflows_uart_buffer"/>
      <xs:element type="xs:boolean" name="config_from_eeprom"/>
      <xs:element type="xs:boolean" name="event_actions_from_eeprom"/>
      <xs:element type="xs:boolean" name="brown_out_warning_level_interrupt_hit"/>
      <xs:element type="xs:boolean" name="lora_overtemperature"/>
      <xs:element type="xs:boolean" name="lora_critical_temperature"/>
      <xs:element type="xs:boolean" name="mbb_satcom_running"/>
      <xs:element type="xs:boolean" name="mbb_cameras_running"/>
      <xs:element type="xs:boolean" name="development_mode"/>
      <xs:element type="xs:boolean" name="servo_sweep_in_progress"/>
      <xs:element type="xs:boolean" name="powerdown_desired"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="ArrayType">
    <xs:sequence>
      <xs:element type="xs:unsignedInt" name="Element0"/>
      <xs:element type="xs:unsignedInt" name="Element1"/>
      <xs:element type="xs:unsignedInt" name="Element2"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="Servo_posType">
    <xs:sequence>
      <xs:element type="ArrayType" name="Array"/>
    </xs:sequence>
  </xs:complexType>
  <!-- Not Done -->
  <xs:complexType name="StatusType">
    <xs:sequence>
      <xs:element type="FlagsType" name="Flags"/>
      <xs:element type="xs:unsignedLong" name="Timestamp"/>
      <xs:element type="xs:unsignedInt" name="Rocket_state"/>
      <xs:element type="xs:unsignedInt" name="Flight_substate"/>
      <xs:element type="Servo_posType" name="Servo_pos"/>
      <xs:element type="xs:unsignedInt" name="Sepadet_adc_value"/>
      <xs:element type="xs:unsignedInt" name="Radio_tx_byte_counter"/>
      <xs:element type="xs:unsignedInt" name="Flash_adr"/>
      <xs:element type="xs:string" name="Seven_segment_value"/>
      <xs:element type="xs:unsignedInt" name="Cpu_load"/>
      <xs:element type="xs:unsignedInt" name="Igniter_adc_voltage"/>
      <xs:element type="xs:unsignedInt" name="Liftoff_timestamp"/>
      <xs:element type="xs:unsignedInt" name="Apogee_timestamp"/>
      <xs:element type="xs:unsignedInt" name="Mainchute_timestamp"/>
      <xs:element type="xs:unsignedLong" name="Landing_timestamp"/>
      <xs:element type="xs:unsignedInt" name="Igniter_1_voltage"/>
      <xs:element type="xs:unsignedInt" name="Igniter_2_voltage"/>
      <xs:element type="xs:unsignedInt" name="Igniter_3_voltage"/>
      <xs:element type="xs:unsignedInt" name="Igniter_4_voltage"/>
      <xs:element type="xs:unsignedInt" name="Igniter_hpower_voltage"/>
      <xs:element type="xs:string" name="Orientation_of_fms"/>
    </xs:sequence>
    <xs:attribute type="xs:time" name="LocalTimestamp"/>
  </xs:complexType>
  <xs:complexType name="FMSType">
    <xs:sequence>
      <xs:element type="xs:time" name="StartingTime"/>
      <xs:element type="PowerType" name="Power"/>
      <xs:element type="ConnectionQualitySensType" name="ConnectionQualitySens"/>
      <xs:element type="StatusType" name="Status"/>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== SpaceTeam/fms-gui-web/fms-gui-web/src/assets/xml/FMS_template.xml
<?xml version="1.0" encoding="UTF-8"?>
<FMS
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="FMS.xsd">
  <StartingTime>15:03:07</StartingTime>
  <Power LocalTimestamp="15:03:37">
    <Voltage>0.000</Voltage>
    <VoltageCell>0.000</VoltageCell>
    <Current>0.000</Current>
  </Power>
  <ConnectionQualitySens LocalTimestamp="15:03:39">
    <Quality>1.000</Quality>
  </ConnectionQualitySens>
  <Status LocalTimestamp="15:03:40">
    <Flags>
      <adc_initialized>true</adc_initialized>
      <dac_initialized>true</dac_initialized>
      <dma_initialized>true</dma_initialized>
      <flash_ssp_initialized>true</flash_ssp_initialized>
      <i2c0_initialized>true</i2c0_initialized>
      <i2c1_initialized>true</i2c1_initialized>
      <i2c2_initialized>true</i2c2_initialized>
      <uart0_initialized>true</uart0_initialized>
      <uart1_initialized>true</uart1_initialized>
      <uart2_initialized>false</uart2_initialized>
      <uart3_initialized>true</uart3_initialized>
      <rtc_initialized>true</rtc_initialized>
      <ssp1_initialized>true</ssp1_initialized>
      <structs_initialized>true</structs_initialized>
      <systick_initialized>true</systick_initialized>
      <timer1_initialized>true</timer1_initialized>
      <watchdog_initialized>true</watchdog_initialized>
      <eeprom_initialized>true</eeprom_initialized>
      <ars_initialized>false</ars_initialized>
      <power_management_initialized>true</power_management_initialized>
      <flash_initialized>true</flash_initialized>
      <seven_segment_intern_initialized>true</seven_segment_intern_initialized>
      <seven_segment_extern_initialized>false</seven_segment_extern_initialized>
      <startup_success>true</startup_success>
      <sensor_pressure_initialized>true</sensor_pressure_initialized>
      <startup_checked>true</startup_checked>
      <sensor_imu_initialized>true</sensor_imu_initialized>
      <sensor_tmp100_initialized>false</sensor_tmp100_initialized>
      <sensor_hig_initialized>true</sensor_hig_initialized>
      <sensor_gyro_initialized>true</sensor_gyro_initialized>
      <gnss_initialized>true</gnss_initialized>
      <servo_initialized_all>false</servo_initialized_all>
      <pwm_initialized>true</pwm_initialized>
      <afs_initialized>true</afs_initialized>
      <camera_initialized>false</camera_initialized>
      <sensor_current_initialized>false</sensor_current_initialized>
      <igniter_initialized>true</igniter_initialized>
      <separation_detection_initialized>true</separation_detection_initialized>
      <servo_configured>false</servo_configured>
      <igniter_configured>true</igniter_configured>
      <igniter_1_fired>false</igniter_1_fired>
      <igniter_2_fired>false</igniter_2_fired>
      <igniter_3_fired>false</igniter_3_fired>
      <igniter_4_fired>false</igniter_4_fired>
      <igniter_1_firing>false</igniter_1_firing>
      <igniter_2_firing>false</igniter_2_firing>
      <igniter_3_firing>false</igniter_3_firing>
      <igniter_4_firing>false</igniter_4_firing>
      <igniter_armed>false</igniter_armed>
      <igniter_1_connected>false</igniter_1_connected>
      <igniter_2_connected>false</igniter_2_connected>
      <igniter_3_connected>false</igniter_3_connected>
      <igniter_4_connected>false</igniter_4_connected>
      <ars_enabled>false</ars_enabled>
      <camera_on>false</camera_on>
      <gnss_powersave>false</gnss_powersave>
      <flash_erased>false</flash_erased>
      <flash_store_data>false</flash_store_data>
      <radio_on>true</radio_on>
      <radio_tx_active>true</radio_tx_active>
      <flash_flight_header_written>false</flash_flight_header_written>
      <timer1_running>true</timer1_running>
      <rtc_synchronized>false</rtc_synchronized>
      <usb_connection_detected>true</usb_connection_detected>
      <watchdog_timeout_occured>false</watchdog_timeout_occured>
      <flash_full>false</flash_full>
      <crystal_oszillator_used>true</crystal_oszillator_used>
      <liftoff_detected>false</liftoff_detected>
      <gnss_fix>false</gnss_fix>
      <rocket_panic>false</rocket_panic>
      <mainchute_altitude_detected>false</mainchute_altitude_detected>
      <eagle_landed>false</eagle_landed>
      <rocket_is_stable>true</rocket_is_stable>
      <apogee_detected_by_kalman>false</apogee_detected_by_kalman>
      <recovery_mode>false</recovery_mode>
      <check_stability_executed>false</check_stability_executed>
      <config_intialized>true</config_intialized>
      <stages_separated>true</stages_separated>
      <igniter_hpower_fired>false</igniter_hpower_fired>
      <igniter_hpower_firing>false</igniter_hpower_firing>
      <igniter_hpower_connected>false</igniter_hpower_connected>
      <reset_during_flight>false</reset_during_flight>
      <housekeeping_data_read>true</housekeeping_data_read>
      <mbb_satcom_configured>true</mbb_satcom_configured>
      <mbb_satcom_initialized>true</mbb_satcom_initialized>
      <mbb_cameras_configured>true</mbb_cameras_configured>
      <mbb_cameras_initialized>true</mbb_cameras_initialized>
      <power_management_operational>false</power_management_operational>
      <rail_5v_enabled>true</rail_5v_enabled>
      <padding1>false</padding1>
      <padding2>false</padding2>
      <battery_overvoltage>false</battery_overvoltage>
      <battery_only_attached>false</battery_only_attached>
      <rail_3v3_sensor_enabled>true</rail_3v3_sensor_enabled>
      <rail_3v3_gnss_enabled>true</rail_3v3_gnss_enabled>
      <rail_3v3_external_enabled>true</rail_3v3_external_enabled>
      <cmd_buffer_overrun>false</cmd_buffer_overrun>
      <eeprom_page_cycle_overflow>false</eeprom_page_cycle_overflow>
      <flash_dma_buffer_overrun>false</flash_dma_buffer_overrun>
      <flash_write_error>false</flash_write_error>
      <i2c_job_buffer_overflow>false</i2c_job_buffer_overflow>
      <i2c_interrupt_handler_error>false</i2c_interrupt_handler_error>
      <interrupt_interference>false</interrupt_interference>
      <uart0_tx_buffer_overflow>false</uart0_tx_buffer_overflow>
      <uart0_rx_buffer_overflow>false</uart0_rx_buffer_overflow>
      <uart1_tx_buffer_overflow>false</uart1_tx_buffer_overflow>
      <uart1_rx_buffer_overflow>false</uart1_rx_buffer_overflow>
      <uart2_tx_buffer_overflow>false</uart2_tx_buffer_overflow>
      <uart2_rx_buffer_overflow>false</uart2_rx_buffer_overflow>
      <uart3_tx_buffer_overflow>false</uart3_tx_buffer_overflow>
      <uart3_rx_buffer_overflow>false</uart3_rx_buffer_overflow>
      <ssp1_interrupt_ror>false</ssp1_interrupt_ror>
      <ssp1_interrupt_unknown_device>false</ssp1_interrupt_unknown_device>
      <ssp1_buffer_overflow>false</ssp1_buffer_overflow>
      <watchdog_interrupt_handler_hit>false</watchdog_interrupt_handler_hit>
      <flight_substate_default_handler_hit>false</flight_substate_default_handler_hit>
      <rocket_state_default_handler_hit>false</rocket_state_default_handler_hit>
      <struct_size_overflows_uart_buffer>false</struct_size_overflows_uart_buffer>
      <config_from_eeprom>true</config_from_eeprom>
      <event_actions_from_eeprom>true</event_actions_from_eeprom>
      <brown_out_warning_level_interrupt_hit>false</brown_out_warning_level_interrupt_hit>
      <lora_overtemperature>false</lora_overtemperature>
      <lora_critical_temperature>false</lora_critical_temperature>
      <mbb_satcom_running>false</mbb_satcom_running>
      <mbb_cameras_running>false</mbb_cameras_running>
      <development_mode>true</development_mode>
      <servo_sweep_in_progress>false</servo_sweep_in_progress>
      <powerdown_desired>false</powerdown_desired>
    </Flags>
    <Timestamp>571991</Timestamp>
    <Rocket_state>1</Rocket_state>
    <Flight_substate>0</Flight_substate>
    <Servo_pos>
      <Array>
        <Element0>0</Element0>
        <Element1>0</Element1>
        <Element2>0</Element2>
      </Array>
    </Servo_pos>
    <Sepadet_adc_value>4095</Sepadet_adc_value>
    <Radio_tx_byte_counter>0</Radio_tx_byte_counter>
    <Flash_adr>0</Flash_adr>
    <Seven_segment_value>U</Seven_segment_value>
    <Cpu_load>0</Cpu_load>
    <Igniter_adc_voltage>0</Igniter_adc_voltage>
    <Liftoff_timestamp>0</Liftoff_timestamp>
    <Apogee_timestamp>0</Apogee_timestamp>
    <Mainchute_timestamp>0</Mainchute_timestamp>
    <Landing_timestamp>0</Landing_timestamp>
    <Igniter_1_voltage>0</Igniter_1_voltage>
    <Igniter_2_voltage>0</Igniter_2_voltage>
    <Igniter_3_voltage>0</Igniter_3_voltage>
    <Igniter_4_voltage>0</Igniter_4_voltage>
    <Igniter_hpower_voltage>633</Igniter_hpower_voltage>
    <Orientation_of_fms>Y_PLUS</Orientation_of_fms>
  </Status>
</FMS>
